name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install boost and z3
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install -y libboost-all-dev
        wget https://github.com/Z3Prover/z3/archive/refs/tags/z3-4.12.1.tar.gz
        tar -xzf z3-4.12.1.tar.gz
        cd z3-4.12.1
        python scripts/mk_make.py
        cd build
        make
        sudo make install
    - name: Build Solidity
      run: ./scripts/build.sh
